### ISSUE TITLE
添加具体的习题条目

### ISSUE THREAD

**Issue by kulernil** [SunyanLBJ23/C-xiti12138#1]
[顺序结构习题.txt](https://github.com/SunyanLBJ23/C-xiti12138/files/3828535/default.txt)

**Comment by SunyanLBJ23** [comment]
> [顺序结构习题.txt](https://github.com/SunyanLBJ23/C-xiti12138/files/3828535/default.txt)

你的文档我已经收到

**Comment by kulernil** [comment]
很好，干得漂亮。

**Comment by kulernil** [comment]
还有三个。

[FOR语句习题.txt](https://github.com/SunyanLBJ23/C-xiti12138/files/3828542/FOR.txt)
[While语句习题.txt](https://github.com/SunyanLBJ23/C-xiti12138/files/3828543/While.txt)
[if语句习题.txt](https://github.com/SunyanLBJ23/C-xiti12138/files/3828544/if.txt)
